import type { NextPage } from "next";
import Head from "next/head";

import "../services/firebase";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>LetMeAsk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World</h1>
      </main>
    </div>
  );
};

export default Home;
